name: Debian packaging

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Debian packaging tools
      run: sudo apt-get install --no-install-suggests --yes build-essential devscripts quilt dh-make equivs
    - name: Install Debian package build dependencies
      run: sudo mk-build-deps --install --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control
    - name: Build Debian package
      run: dpkg-buildpackage -us -uc -b

# See https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.en.pdf
