# See https://www.debian.org/doc/manuals/packaging-tutorial/packaging-tutorial.en.pdf

name: Debian packaging

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Debian packaging tools
      run: sudo apt-get install -y build-essential devscripts quilt dh-make
    - name: Install Debian package build dependencies
      run: sudo mk-build-deps --install --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control
    - name: Build Debian package
      run: dpkg-buildpackage -us -uc
